---
- name: install extra packages
  apt:
    name: "{{ extra_packages }}"
    state: present

- name: Adding user www-data to group shadow for nginx pam
  user:
    name: www-data
    groups: shadow
    append: yes
