---
- hosts: cloud
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - default_user
    - setup
    - xfce4-desktop
    - guacamole
    - nginx
    - certbot
    - config
    - facts
    - cleanup
